import type { SeedUnit } from '../types.js';

export const SEED_CURRICULUM: SeedUnit[] = [
  {
    id: 'dsa-001',
    type: 'unit',
    title: '数组与双指针：用两个游标压缩无效操作',
    description: '学习如何用双指针在有序数组上原地去重，并理解时间复杂度 O(n) 的来源。',
    prerequisites: ['数组基础', 'for 循环', '基本时间复杂度概念'],
    objectives: [
      '理解双指针适合处理有序或可线性扫描的问题',
      '能解释 slow/fast 两个指针分别代表什么',
      '能实现原地数组去重并返回有效长度',
    ],
    content: [
      '# 数组与双指针：用两个游标压缩无效操作',
      '',
      '## 1. 为什么需要双指针？',
      '',
      '如果你要在有序数组里删除重复元素，最直观的方法可能是：遍历数组、遇到重复就删除、继续向后检查。',
      '但数组删除元素会让后面的元素整体移动，成本很高。双指针的核心思想是：不要真的删除，而是把需要保留的元素紧凑地搬到数组前面。',
      '',
      '## 2. slow / fast 指针模型',
      '',
      '- `fast`：负责向前探索，查看新元素',
      '- `slow`：指向下一个应该写入保留元素的位置',
      '',
      '当 `nums[fast] !== nums[slow]` 时，说明发现了一个新值：slow 向前移动一格，然后把 `nums[fast]` 写到 `nums[slow]`。',
      '最后 `slow + 1` 就是去重后有效部分的长度。',
      '',
      '## 3. 示例',
      '',
      '输入：`[1, 1, 2, 2, 3]`。',
      '过程：fast 从 1 开始扫描；遇到重复值就跳过；遇到新值就写入 slow 的下一个位置。',
      '最终前三个元素变为 `[1, 2, 3]`，返回长度 3。',
      '',
      '## 4. 代码模板',
      '',
      '```ts',
      'export function removeDuplicates(nums: number[]): number {',
      '  if (nums.length === 0) return 0;',
      '  let slow = 0;',
      '  for (let fast = 1; fast < nums.length; fast++) {',
      '    if (nums[fast] !== nums[slow]) {',
      '      slow++;',
      '      nums[slow] = nums[fast];',
      '    }',
      '  }',
      '  return slow + 1;',
      '}',
      '```',
      '',
      '## 5. 你要完成的练习',
      '',
      '实现 `removeDuplicates(nums: number[]): number`。',
      '要求：不要创建新数组；原地修改 `nums`；返回去重后的有效长度；空数组返回 0。',
      '',
      '## 6. 小测',
      '',
      '1. 双指针为什么适合有序数组去重？',
      '2. `slow` 指针代表什么？',
      '3. 为什么返回值是 `slow + 1` 而不是 `slow`？',
      '',
      '## 7. 参考设计来源',
      '',
      '- CS61A：强调通过小 lab 建立直觉',
      '- UC Berkeley Data Structures：重视测试驱动的数据结构练习',
      '- freeCodeCamp：用闯关反馈帮助学习者持续修正',
    ].join('\n'),
    references: [
      'https://cs61a.org/',
      'https://sp26.datastructur.es/',
      'https://www.freecodecamp.org/learn/front-end-development-libraries/#bootstrap/',
    ],
    quiz: [
      {
        id: 'q1',
        type: 'choice',
        question: '双指针最适合解决哪类问题？',
        options: [
          '必须枚举所有排列的问题',
          '可以在线性扫描中维护两个位置的问题',
          '只能递归解决的问题',
          '必须使用哈希表的问题',
        ],
        answer: '可以在线性扫描中维护两个位置的问题',
        explanation: '双指针本质是在一次线性扫描中维护两个有意义的索引。',
      },
      {
        id: 'q2',
        type: 'choice',
        question: '在原地去重中，slow 指针代表什么？',
        options: [
          '当前正在探索的元素',
          '下一个保留元素应该写入的位置',
          '数组最后一个元素的位置',
          '重复元素的个数',
        ],
        answer: '下一个保留元素应该写入的位置',
        explanation: 'fast 探索，slow 写入。',
      },
      {
        id: 'q3',
        type: 'short-answer',
        question: '为什么返回 slow + 1？',
        answer: '因为 slow 是最后一个保留元素的索引，长度等于索引加一。',
        explanation: '索引从 0 开始，所以长度需要加一。',
      },
    ],
    exercise: {
      id: 'ex-dsa-001',
      language: 'typescript',
      entrypoint: 'removeDuplicates',
      description: '实现有序数组原地去重，并返回去重后的有效长度。',
      assertionMode: 'mutate-and-return',
      starterCode: `export function removeDuplicates(nums: number[]): number {
  // TODO: implement removeDuplicates
  return 0;
}
`,
      testCases: [
        { name: 'empty array', input: [[]], expected: { k: 0, nums: [] } },
        { name: 'single element', input: [[1]], expected: { k: 1, nums: [1] } },
        { name: 'all duplicates', input: [[1, 1, 1]], expected: { k: 1, nums: [1, 1, 1] } },
        { name: 'mixed duplicates', input: [[1, 1, 2, 2, 3]], expected: { k: 3, nums: [1, 2, 3, 2, 3] } },
      ],
      hints: ['先处理空数组。', '让 fast 从 1 开始。', '只有当 fast 指向新值时，slow 才前进。'],
    },
    passCriteria: { quizMinScore: 2, exerciseMustPass: true },
    nextIfPassed: 'dsa-002',
    nextIfFailed: 'dsa-001',
  },
  {
    id: 'dsa-002',
    type: 'unit',
    title: '哈希表：把查找从线性扫描变成常数时间',
    description: '学习 Map/Set 如何帮助你用空间换时间，解决 two-sum 类问题。',
    prerequisites: ['数组遍历', '对象/Map 基础', '时间复杂度 O(n)'],
    objectives: [
      '理解哈希表为什么能降低查找成本',
      '能用 Map 记录值到索引的映射',
      '能实现 twoSum 并解释一次遍历解法',
    ],
    content: [
      '# 哈希表：把查找从线性扫描变成常数时间',
      '',
      '## 1. 问题',
      '',
      '给定数组 `nums` 和目标值 `target`，找出两个数，使它们的和等于 `target`，并返回它们的下标。',
      '例如 `nums = [2, 7, 11, 15]`，`target = 9`，答案是 `[0, 1]`。',
      '',
      '## 2. 暴力思路的问题',
      '',
      '双重循环的时间复杂度是 O(n²)。当数组变大时，会非常慢。',
      '',
      '## 3. 用 Map 换时间',
      '',
      '我们真正需要知道的是：当前数字 `num` 的搭档 `target - num` 之前有没有出现过？',
      '如果出现过，就直接返回两个下标。因此可以用 Map 保存 `value -> index`。',
      '',
      '## 4. 一次遍历模板',
      '',
      '```ts',
      'export function twoSum(nums: number[], target: number): number[] {',
      '  const seen = new Map<number, number>();',
      '  for (let i = 0; i < nums.length; i++) {',
      '    const complement = target - nums[i];',
      '    if (seen.has(complement)) {',
      '      return [seen.get(complement)!, i];',
      '    }',
      '    seen.set(nums[i], i);',
      '  }',
      '  throw new Error("No solution found");',
      '}',
      '```',
      '',
      '## 5. 你要完成的练习',
      '',
      '实现 `twoSum(nums: number[], target: number): number[]`。',
      '要求：返回两个下标；假设每组输入都有唯一解；不要重复使用同一个元素。',
      '',
      '## 6. 小测',
      '',
      '1. Map 里存的是 index -> value 还是 value -> index？',
      '2. 为什么一次遍历就能找到答案？',
      '3. 空间复杂度是多少？',
      '',
      '## 7. 参考设计来源',
      '',
      '- Full Stack Open：强调先理解问题，再写最小可运行代码',
      '- CS61A：用小例子建立抽象思维',
      '- freeCodeCamp：通过即时反馈强化练习',
    ].join('\n'),
    references: ['https://fullstackopen.com/en/', 'https://cs61a.org/', 'https://www.freecodecamp.org/learn/front-end-development-libraries/#bootstrap/'],
    quiz: [
      {
        id: 'q1',
        type: 'choice',
        question: 'twoSum 中 Map 最适合保存什么？',
        options: ['value -> index', 'index -> value', 'target -> nums', 'i -> j'],
        answer: 'value -> index',
        explanation: '我们需要根据 complement 快速找到之前出现过的下标。',
      },
      {
        id: 'q2',
        type: 'choice',
        question: '一次遍历 twoSum 的时间复杂度是多少？',
        options: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'],
        answer: 'O(n)',
        explanation: '每个元素最多访问一次。',
      },
      {
        id: 'q3',
        type: 'short-answer',
        question: '为什么不能先 set 当前元素再检查 complement？',
        answer: '因为可能错误地把当前元素当成自己的 complement 使用。',
        explanation: '题目要求不能使用同一个元素两次。',
      },
    ],
    exercise: {
      id: 'ex-dsa-002',
      language: 'typescript',
      entrypoint: 'twoSum',
      description: '实现 twoSum，返回和为 target 的两个下标。',
      assertionMode: 'return',
      starterCode: `export function twoSum(nums: number[], target: number): number[] {
  // TODO: implement twoSum
  return [];
}
`,
      testCases: [
        { name: 'basic example', input: [[2, 7, 11, 15], 9], expected: [0, 1] },
        { name: 'negative numbers', input: [[-1, -2, -3, -4, -5], -8], expected: [2, 4] },
        { name: 'zero included', input: [[0, 4, 3, 0], 0], expected: [0, 3] },
      ],
      hints: ['遍历数组时，先查 complement。', 'Map 保存 value -> index。', '找到答案后立即 return。'],
    },
    passCriteria: { quizMinScore: 2, exerciseMustPass: true },
    nextIfPassed: 'dsa-003',
    nextIfFailed: 'dsa-002',
  },
  {
    id: 'dsa-003',
    type: 'unit',
    title: '栈与括号匹配：用 LIFO 表达嵌套结构',
    description: '学习栈的后进先出特性，并用它解决括号匹配问题。',
    prerequisites: ['数组基础', 'Map 基础', '函数调用直觉'],
    objectives: [
      '理解栈的后进先出 LIFO 特性',
      '能用栈判断括号是否正确嵌套',
      '能解释为什么右括号必须匹配最近的左括号',
    ],
    content: [
      '# 栈与括号匹配：用 LIFO 表达嵌套结构',
      '',
      '## 1. 什么是栈？',
      '',
      '栈是一种后进先出的数据结构，英文叫 Last In First Out，简称 LIFO。',
      '常见操作：`push` 入栈，`pop` 出栈，`peek` 查看栈顶。',
      '',
      '## 2. 括号匹配为什么需要栈？',
      '',
      '括号具有嵌套关系，例如 `([{}])`。最右边的左括号 `{` 必须最先被匹配，这正是栈的特性。',
      '当你遇到右括号时，它必须匹配最近一个还没匹配的左括号。',
      '',
      '## 3. 判断规则',
      '',
      '1. 遇到左括号，入栈',
      '2. 遇到右括号：如果栈为空则失败；弹出栈顶；检查是否匹配',
      '3. 遍历结束后，栈必须为空',
      '',
      '## 4. 模板',
      '',
      '```ts',
      'export function isValidParentheses(s: string): boolean {',
      '  const stack: string[] = [];',
      "  const pairs: Record<string, string> = { ')': '(', ']': '[', '}': '{' };",
      '  for (const ch of s) {',
      '    if (ch === \'(\' || ch === \'[\' || ch === \'{\') {',
      '      stack.push(ch);',
      '    } else {',
      '      const top = stack.pop();',
      '      if (top !== pairs[ch]) {',
      '        return false;',
      '      }',
      '    }',
      '  }',
      '  return stack.length === 0;',
      '}',
      '```',
      '',
      '## 5. 你要完成的练习',
      '',
      '实现 `isValidParentheses(s: string): boolean`。',
      '要求：只处理 `()`、`[]`、`{}`；空字符串视为有效；右括号必须匹配最近的左括号。',
      '',
      '## 6. 小测',
      '',
      '1. 栈的核心特性是什么？',
      '2. 为什么右括号要匹配最近的左括号？',
      '3. 遍历结束后栈为空说明什么？',
      '',
      '## 7. 参考设计来源',
      '',
      '- Data Structures 课程中的 lab/test 组织方式',
      '- CS61A 对递归和栈直觉的铺垫',
      '- The Odin Project 的项目式练习节奏',
    ].join('\n'),
    references: ['https://sp26.datastructur.es/', 'https://cs61a.org/', 'https://www.theodinproject.com/'],
    quiz: [
      {
        id: 'q1',
        type: 'choice',
        question: '栈的核心特性是什么？',
        options: ['先进先出 FIFO', '后进先出 LIFO', '随机访问', '只能访问中间元素'],
        answer: '后进先出 LIFO',
        explanation: '最后进入的元素最先离开。',
      },
      {
        id: 'q2',
        type: 'choice',
        question: '遇到右括号时，应该检查什么？',
        options: ['数组第一个元素', '最近一个未匹配的左括号', '字符串最后一个字符', '目标值 complement'],
        answer: '最近一个未匹配的左括号',
        explanation: '这正是栈顶元素。',
      },
      {
        id: 'q3',
        type: 'short-answer',
        question: '遍历结束后栈为空说明什么？',
        answer: '说明所有左括号都被正确匹配。',
        explanation: '如果栈不为空，说明还有未匹配的左括号。',
      },
    ],
    exercise: {
      id: 'ex-dsa-003',
      language: 'typescript',
      entrypoint: 'isValidParentheses',
      description: '判断括号字符串是否正确嵌套。',
      assertionMode: 'return',
      starterCode: `export function isValidParentheses(s: string): boolean {
  // TODO: implement isValidParentheses
  return true;
}
`,
      testCases: [
        { name: 'empty string', input: [''], expected: true },
        { name: 'simple valid', input: ['()[]{}'], expected: true },
        { name: 'nested valid', input: ['([{}])'], expected: true },
        { name: 'invalid order', input: ['([)]'], expected: false },
        { name: 'missing close', input: ['(()'], expected: false },
      ],
      hints: ['左括号入栈。', '右括号弹出栈顶并检查是否匹配。', '遍历结束后栈必须为空。'],
    },
    passCriteria: { quizMinScore: 2, exerciseMustPass: true },
    nextIfPassed: 'dsa-project-bracket-dungeon',
  },
  {
    id: 'dsa-project-bracket-dungeon',
    type: 'project',
    title: 'Project：括号地牢路线审计器',
    description: '综合数组、哈希表和栈，构建一个能给嵌套路线判定有效性并计算分数的小型规则引擎。',
    prerequisites: ['数组与双指针', '哈希表', '栈与括号匹配'],
    objectives: [
      '能把项目需求拆成数据模型、规则映射和状态转移',
      '能使用栈验证嵌套结构并用哈希表表达匹配规则',
      '能根据测试反馈逐步完成一个小型 CS61A 风格项目',
    ],
    content: [
      '# Project：括号地牢路线审计器',
      '',
      '你要写一个小型规则引擎：输入一串由 `()[]{}` 组成的地牢路线，判断路线是否合法，并为每一对成功闭合的房间计分。',
      '圆括号代表普通房间，计 1 分；方括号代表机关房，计 2 分；花括号代表宝藏房，计 3 分。路线可以嵌套，但每个出口必须匹配最近进入的房间。',
      '',
      '## 为什么这是一个 Project 而不是一道题？',
      '',
      '因为你不只是在“写括号匹配”。你需要把需求分解成三个小模块：',
      '',
      '- **规则表**：用哈希表描述 `)` 应该匹配 `(`，以及每类房间的分数。',
      '- **状态栈**：用数组模拟进入/离开房间的过程。',
      '- **审计结果**：用一个稳定的返回对象表达路线是否有效和最终分数。',
      '',
      '这个项目的核心不在代码长度，而在设计纪律：每一步都应该能被测试解释。若出现 `([)]`，系统必须发现“出口匹配了错误的最近房间”；若最后栈里还留着 `(`，系统必须判定路线未闭合。',
      '',
      '## 推荐实现路线',
      '',
      '1. 先建立 `closingToOpening` 和 `openingScores` 两张表。',
      '2. 遍历字符串，跳过空白字符。',
      '3. 遇到入口括号就入栈。',
      '4. 遇到出口括号就检查栈顶是否匹配；匹配则计分，不匹配直接失败。',
      '5. 遍历结束后，只有栈为空才算合法。',
      '',
      '写完后执行 `fc submit dsa-project-bracket-dungeon`，用本地测试检查你的规则引擎。',
    ].join('\n'),
    references: ['https://cs61a.org/', 'https://sp26.datastructur.es/'],
    quiz: [
      {
        id: 'q1',
        type: 'choice',
        question: '为什么路线 `([)]` 必须被判定为无效？',
        options: [
          '因为它包含方括号',
          '因为右括号必须匹配最近尚未关闭的左括号',
          '因为所有括号都不能嵌套',
          '因为圆括号不能计分',
        ],
        answer: '因为右括号必须匹配最近尚未关闭的左括号',
        explanation: '栈顶代表最近尚未关闭的房间，`)` 不能关闭 `[`。',
      },
      {
        id: 'q2',
        type: 'choice',
        question: '本项目中哈希表最适合用来表达什么？',
        options: ['测试结果输出', '括号匹配关系和分数规则', '循环次数', '文件路径'],
        answer: '括号匹配关系和分数规则',
        explanation: '规则映射是哈希表最自然的用法。',
      },
      {
        id: 'q3',
        type: 'short-answer',
        question: '遍历结束后为什么还要检查栈是否为空？',
        answer: '因为栈不为空说明还有入口房间没有被正确关闭。',
        explanation: '例如 `(()` 在遍历过程中没有 mismatch，但仍然是不完整路线。',
      },
    ],
    exercise: {
      id: 'ex-dsa-project-bracket-dungeon',
      language: 'typescript',
      entrypoint: 'gradeBracketDungeon',
      description: '实现括号地牢路线审计器，返回路线是否合法以及成功闭合房间的总分。',
      assertionMode: 'return',
      starterCode: `export interface DungeonAudit {
  valid: boolean;
  score: number;
}

/**
 * Audit a bracket dungeon route.
 *
 * Scoring rules:
 * - () is worth 1 point
 * - [] is worth 2 points
 * - {} is worth 3 points
 * - Whitespace is ignored
 * - Any mismatched or unfinished route is invalid and scores 0
 *
 * Examples:
 * >>> gradeBracketDungeon("()[]")
 * { valid: true, score: 3 }
 * >>> gradeBracketDungeon("([)]")
 * { valid: false, score: 0 }
 */
export function gradeBracketDungeon(route: string): DungeonAudit {
  const openingStack: string[] = [];
  const closingToOpening: Record<string, string> = {
    ')': '(',
    ']': '[',
    '}': '{',
  };
  const openingScores: Record<string, number> = {
    '(': 1,
    '[': 2,
    '{': 3,
  };

  // TODO: Step 1 - keep a running score for every correctly closed room.
  // TODO: Step 2 - scan each character, ignoring whitespace.
  // TODO: Step 3 - push opening room markers onto openingStack.
  // TODO: Step 4 - when you see a closing marker, compare it with the stack top.
  // TODO: Step 5 - only return valid: true if the stack is empty at the end.

  return { valid: false, score: 0 };
}
`,
      testCases: [
        { name: 'sequential rooms', input: ['()[]'], expected: { valid: true, score: 3 } },
        { name: 'deep nested treasure route', input: ['({[]})'], expected: { valid: true, score: 6 } },
        { name: 'misordered exit', input: ['([)]'], expected: { valid: false, score: 0 } },
        { name: 'unfinished route', input: ['(()'], expected: { valid: false, score: 0 } },
        { name: 'whitespace ignored', input: ['( [ ] )'], expected: { valid: true, score: 3 } },
      ],
      hints: [
        '栈顶永远代表最近进入但还没离开的房间。',
        '遇到关闭括号时，先查 closingToOpening，再和 stack.pop() 的结果比较。',
        '计分最好根据被成功关闭的 opening bracket 查询 openingScores。',
      ],
    },
    project: {
      id: 'project-dsa-bracket-dungeon',
      title: '括号地牢路线审计器',
      narrative: '你正在为一个文本地牢构建路线审计器：每条路线都必须正确进出房间，系统还要根据房间类型计算奖励分。',
      drivingQuestion: '如何把一串括号路线拆成规则表、状态栈和可测试的审计结果？',
      deliverables: [
        '完成 `gradeBracketDungeon(route)` 的实现',
        '通过所有本地测试，包括嵌套、错序、未闭合和空白输入',
        '能用一句话解释哈希表和栈各自承担的职责',
      ],
      milestones: [
        {
          id: 'phase-1-rule-map',
          title: 'Phase 1: 建立规则表',
          goal: '用哈希表清晰表达括号匹配关系和分数规则。',
          learnerTasks: ['阅读 starter code 中的两张表', '确认每种入口和出口括号的含义'],
          acceptanceCriteria: ['能解释 `closingToOpening[")"]` 为什么等于 `"("`', '能解释 `{}` 为什么计 3 分'],
        },
        {
          id: 'phase-2-stack-state',
          title: 'Phase 2: 实现状态栈',
          goal: '用数组栈追踪最近尚未关闭的房间。',
          learnerTasks: ['遇到入口括号时 push', '遇到出口括号时 pop 并比较'],
          acceptanceCriteria: ['`({[]})` 能被判定为有效', '`([)]` 能被判定为无效'],
        },
        {
          id: 'phase-3-audit-result',
          title: 'Phase 3: 输出稳定审计结果',
          goal: '把合法性和分数封装成稳定对象，方便后续项目扩展。',
          learnerTasks: ['只在成功匹配时累加分数', '结束时检查栈是否清空', '保持无效路线返回 `{ valid: false, score: 0 }`'],
          acceptanceCriteria: ['未闭合路线返回无效', '带空白的合法路线仍能通过'],
        },
      ],
      files: [
        { path: 'PROJECT.md', purpose: '项目规格、阶段、评分标准和扩展挑战。', required: true },
        { path: 'solution.ts', purpose: '主实现文件，包含 `gradeBracketDungeon`。', required: true },
        { path: 'test.ts', purpose: '提交时由本地 runner 生成的测试文件。', required: false },
      ],
      rubric: [
        { criterion: 'Correctness', points: 4, evidence: '所有本地测试通过，尤其是错序和未闭合路线。' },
        { criterion: 'Design', points: 3, evidence: '规则表、状态栈、返回对象职责清楚。' },
        { criterion: 'Explanation', points: 3, evidence: '能解释为什么这个项目同时使用哈希表和栈。' },
      ],
      extensionIdeas: [
        '加入普通字符作为地牢路径节点，并忽略它们或把它们计入日志。',
        '返回第一处错误的位置，帮助玩家定位路线问题。',
        '把分数规则改成可配置参数，练习更深的接口设计。',
      ],
    },
    passCriteria: { quizMinScore: 2, exerciseMustPass: true },
    nextIfFailed: 'dsa-project-bracket-dungeon',
  },
];

export function getSeedUnit(unitId: string): SeedUnit | undefined {
  return SEED_CURRICULUM.find((unit) => unit.id === unitId);
}
