import fs from 'node:fs';
import path from 'node:path';
import type { ExerciseSpec, TestResult } from '../types.js';
import { getExtensionForLanguage } from '../utils/paths.js';
import type { ExerciseRunResult } from './types.js';

interface PistonRuntime {
  language: string;
  version: string;
  aliases: string[];
}

interface PistonExecuteResponse {
  language: string;
  version: string;
  run: {
    stdout: string;
    stderr: string;
    code: number;
    signal: string | null;
  };
  compile?: {
    stdout: string;
    stderr: string;
    code: number;
    signal: string | null;
  };
}

let runtimesCache: PistonRuntime[] | null = null;

async function getPistonRuntimes(): Promise<PistonRuntime[]> {
  if (runtimesCache) return runtimesCache;
  const res = await fetch('https://emkc.org/api/v2/piston/runtimes');
  if (!res.ok) {
    throw new Error(`Failed to fetch Piston runtimes: ${res.statusText}`);
  }
  runtimesCache = await res.json() as PistonRuntime[];
  return runtimesCache;
}

export async function runPistonExercise(
  unitId: string,
  exercise: ExerciseSpec,
  exerciseDir: string
): Promise<ExerciseRunResult> {
  const extension = getExtensionForLanguage(exercise.language);
  const solutionPath = path.join(exerciseDir, `solution${extension}`);
  const solutionContent = fs.existsSync(solutionPath) ? fs.readFileSync(solutionPath, 'utf8') : '';

  const files: { name: string; content: string }[] = [];

  // If there's a specific testCode generated by the LLM, we need to include it.
  // We'll name the test file 'test.ext' and put it first so scripting languages execute it by default.
  if (exercise.testCode && exercise.testCode.trim().length > 0) {
    files.push({ name: `test${extension}`, content: exercise.testCode });
  }

  // Add the user's solution code
  files.push({ name: `solution${extension}`, content: solutionContent });

  // Resolve the language version (fallback to '*')
  let version = '*';
  try {
    const runtimes = await getPistonRuntimes();
    const runtime = runtimes.find(
      (r) => r.language === exercise.language || r.aliases.includes(exercise.language)
    );
    if (runtime) {
      version = runtime.version;
    }
  } catch (e) {
    console.warn('Could not fetch runtimes, using version "*"');
  }

  try {
    const res = await fetch('https://emkc.org/api/v2/piston/execute', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        language: exercise.language,
        version,
        files,
        compile_timeout: 10000,
        run_timeout: 5000,
      }),
    });

    if (!res.ok) {
      throw new Error(`Piston execution failed: ${res.status} ${res.statusText}`);
    }

    const data = await res.json() as PistonExecuteResponse;

    let stdout = data.run?.stdout ?? '';
    let stderr = data.run?.stderr ?? '';
    
    if (data.compile && data.compile.code !== 0) {
      stderr = data.compile.stderr || data.compile.stdout || 'Compilation failed';
    }

    const testResults = parseJsonLines(stdout);
    const passed = testResults.length > 0 && testResults.every((r) => r.passed);

    return {
      unitId,
      stdout,
      stderr,
      exitCode: data.run?.code ?? (data.compile?.code ?? null),
      signal: (data.run?.signal as NodeJS.Signals) ?? null,
      testResults: testResults.length > 0 
        ? testResults 
        : [{ name: 'execution', passed: false, message: stderr || 'No test results printed.' }],
      passed,
    };
  } catch (err: any) {
    return {
      unitId,
      stdout: '',
      stderr: err.message,
      exitCode: 1,
      signal: null,
      testResults: [{ name: 'piston-runner', passed: false, message: err.message }],
      passed: false,
    };
  }
}

function parseJsonLines(stdout: string): TestResult[] {
  return stdout
    .split(/\\r?\\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith('{') && line.endsWith('}'))
    .flatMap((line) => {
      try {
        const parsed = JSON.parse(line) as TestResult;
        return [parsed];
      } catch {
        return [];
      }
    });
}
